{snippet}
<div class="gridito">
	{if isset($windowOutput)}

	{* window (non javascript fallback) *}
		{block window}
			<h2>{$windowLabel}</h2>
			{!$windowOutput}
		{/block}

		{else}

		{block grid}

		{* flash messages *}
			{snippet flashes}
				<div n:class="gridito-flash, $flash->type === 'error' ? 'ui-state-error' : 'ui-state-highlight', ui-corner-all" n:foreach="$flashes as $flash">
					<span n:class="gridito-icon, ui-icon, $flash->type === 'error' ? 'ui-icon-alert' : 'ui-icon-info'"></span>
					{$flash->message}
				</div>
			{/snippet}

		{* top toolbar *}
			{block toptoolbar}
				<div class="gridito-toolbar" n:if="$control->hasToolbar()" n:inner-foreach="$control['toolbar']->getComponents() as $button">
					{control $button}
				</div>
			{/block}

		{* table or empty message *}
			{block data}

				{if $control->getModel()->count() > 0}

				{* grid table *}
					{block table}
						<table class="gridito-table">
							<thead>
							<tr>
								{block tableheader}
									{var $nextSort = array(null => 'asc', 'asc' => 'desc', 'desc' => null)}
									<th n:foreach="$control['columns']->getComponents() as $column">
										{block tableheadercontent}
											<span class="gridito-sorting" n:if="$column->isSortable()">
												<a n:if="$column->getSorting() === null" n:href="sort!, $column->getName(), asc" n:class="$control->getAjaxClass()"><span class="sorting-no"></span></a>
												<a n:if="$column->getSorting() === 'asc'" n:href="sort!, $column->getName(), desc" n:class="$control->getAjaxClass()"><span class="sorting-asc"></span></a>
												<a n:if="$column->getSorting() === 'desc'" n:href="sort!, null, null" n:class="$control->getAjaxClass()"><span class="sorting-desc"></span></a>
											</span>
											{$column->getLabel()}
										{/block}
									</th>
									<th n:if="$control->hasActions()"></th>
								{/block}
							</tr>
							</thead>
							<tbody>
								{block tablebody}
								<tr n:foreach="$control->getModel()->getItems() as $item" n:class="$control->getRowClass($iterator, $item)">
									<td n:class="gridito-cell, $column->getCellClass($iterator, item), $control->isColumnHighlighted($column) ? ui-state-highlight" n:foreach="$control['columns']->getComponents() as $column">
										{control $column:cell $item}
									</td>
									<td class="gridito-actioncell" n:if="$control->hasActions()" n:inner-foreach="$control['actions']->getComponents() as $button">
										{control $button $item}
									</td>
								</tr>
								{/block}
							</tbody>
						</table>
					{/block}

					{else}
					{block emptyResult}{/block}
				{/if}

			{/block}

			{control $paginator}

		{/block}
	{/if}
</div>
{/snippet}
